// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcsOAwbGKcRXPYBz-OxxoEx5KA8XAB8SI',
    appId: '1:473966314627:android:66d8997a3fba26243147b6',
    messagingSenderId: '473966314627',
    projectId: 'rota-portali',
    storageBucket: 'rota-portali.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl4_HHOS6CaoPuGjzOAlckQYWQxgeiC2s',
    appId: '1:473966314627:ios:2e866be108d258a43147b6',
    messagingSenderId: '473966314627',
    projectId: 'rota-portali',
    storageBucket: 'rota-portali.appspot.com',
    iosBundleId: 'com.example.backpackPal',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF728rra9M1BuF1kc-EUGgqN3BxN67x-k',
    appId: '1:473966314627:web:61cbb4756b1959a13147b6',
    messagingSenderId: '473966314627',
    projectId: 'rota-portali',
    authDomain: 'rota-portali.firebaseapp.com',
    storageBucket: 'rota-portali.appspot.com',
    measurementId: 'G-8R3W5W0KHG',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAl4_HHOS6CaoPuGjzOAlckQYWQxgeiC2s',
    appId: '1:473966314627:ios:2e866be108d258a43147b6',
    messagingSenderId: '473966314627',
    projectId: 'rota-portali',
    storageBucket: 'rota-portali.appspot.com',
    iosBundleId: 'com.example.backpackPal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF728rra9M1BuF1kc-EUGgqN3BxN67x-k',
    appId: '1:473966314627:web:f39f0ff8ffb3b4603147b6',
    messagingSenderId: '473966314627',
    projectId: 'rota-portali',
    authDomain: 'rota-portali.firebaseapp.com',
    storageBucket: 'rota-portali.appspot.com',
    measurementId: 'G-Q8GJMBKQRL',
  );

}