// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz13scZUWUH1GznJhAvyjXbvcnME20qj4',
    appId: '1:242989011538:android:d2010ddc6dbfcd4c72c58b',
    messagingSenderId: '242989011538',
    projectId: 'healtrack-c1807',
    storageBucket: 'healtrack-c1807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjCcTFjXfF_ApHul57oeBj9hn-yOfJ8_E',
    appId: '1:242989011538:ios:e0c780ca4705691d72c58b',
    messagingSenderId: '242989011538',
    projectId: 'healtrack-c1807',
    storageBucket: 'healtrack-c1807.appspot.com',
    androidClientId: '242989011538-segk582qa7ui6onhjkck88iuijn5qj35.apps.googleusercontent.com',
    iosClientId: '242989011538-dd57anifhfqo3ubr9mk7dnjsh8pm6sir.apps.googleusercontent.com',
    iosBundleId: 'com.example.backpackPal',
  );
}
